---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test
  annotations:
    github.com/project-slug: rusrom/test
schema:
  required: 
    - component_id
    - description
  properties:
    component_id:
      title: Name
      type: string
      description: Unique name of the component. Lowercase, URL-safe characters only.
    description:
      title: Description
      type: string
      description: Help others understand what this website is for.
